#!/usr/bin/env python3
"""
Apply a BTC-UAP to videos.

Given a BTC-UAP tensor (.pt) generated by btc_attack.py, this script:
  1. Reads each source video frame-by-frame.
  2. Repeats the N-frame UAP cyclically to cover all T frames (Eq. 1).
  3. Adds the perturbation:  V_adv^t = clamp(V^t + delta_T^t, 0, 1)
  4. Writes the adversarial video to the output directory.

Temporal smoothing options (for imperceptibility):
  --smooth_sigma S   Gaussian blur the UAP along the time axis (sigma=S).
                     Softens abrupt per-frame pattern changes.
  --stretch F        Slow the UAP playback by factor F with linear
                     interpolation between keyframes.  E.g. --stretch 4
                     makes each UAP frame span 4 video frames with smooth
                     cross-fades between them.

Temporal order ablation (for analysis):
  --shuffle_seed S   Randomly permute the N UAP frames with seed S.
  --static_frame I   Use only UAP frame I for all video frames.
  --reverse          Reverse the UAP frame order.

Usage:
    python apply_uap.py \
        --uap btc_uap.pt \
        --video_dir /path/to/videos \
        --output_dir ./adversarial_videos \
        --smooth_sigma 1.0 \
        --stretch 4
"""

import argparse
import math
import shutil
import subprocess
import sys
from pathlib import Path

import cv2
import numpy as np
import torch
from tqdm import tqdm

VIDEO_EXTENSIONS = {".mp4", ".avi", ".mov", ".mkv", ".wmv", ".flv"}


# ── Temporal smoothing ────────────────────────────────────────────────────


def gaussian_kernel_1d(sigma, truncate=3.0):
    """Create a 1-D Gaussian kernel (normalised, wraps via cyclic padding)."""
    radius = int(math.ceil(sigma * truncate))
    x = np.arange(-radius, radius + 1, dtype=np.float64)
    kernel = np.exp(-0.5 * (x / sigma) ** 2)
    kernel /= kernel.sum()
    return kernel


def temporal_gaussian_smooth(delta_N, sigma, epsilon):
    """
    Apply 1-D Gaussian smoothing along the temporal (frame) axis of the UAP.
    Uses cyclic (wrap-around) padding because the UAP repeats in time.
    Re-clamps to [-epsilon, epsilon] afterwards to preserve the budget.

    delta_N: numpy array of shape (N, C, H, W)
    """
    if sigma <= 0:
        return delta_N

    kernel = gaussian_kernel_1d(sigma)
    radius = len(kernel) // 2
    N = delta_N.shape[0]

    # Cyclic padding along temporal axis
    padded = np.concatenate([delta_N[-radius:], delta_N, delta_N[:radius]], axis=0)

    smoothed = np.zeros_like(delta_N)
    for i in range(N):
        for k, w in enumerate(kernel):
            smoothed[i] += w * padded[i + k]

    # Re-clamp to perturbation budget
    smoothed = np.clip(smoothed, -epsilon, epsilon)
    return smoothed


def get_interpolated_frame(delta_N_np, frame_idx, N, stretch):
    """
    Get the perturbation for a given video frame index.

    Without stretch (stretch=1): hard-select delta_N[frame_idx % N].
    With stretch > 1: linearly interpolate between neighbouring UAP frames.
    E.g. stretch=4 means each UAP frame spans 4 video frames, with smooth
    cross-fades between consecutive keyframes.

    Returns: numpy array of shape (C, H, W)
    """
    if stretch <= 1:
        return delta_N_np[frame_idx % N]

    # Floating-point position within the UAP cycle
    cycle_length = N * stretch
    t = (frame_idx % cycle_length) / stretch   # position in [0, N)

    n_low = int(t) % N
    n_high = (n_low + 1) % N
    alpha = t - int(t)

    return (1.0 - alpha) * delta_N_np[n_low] + alpha * delta_N_np[n_high]


# ── Video I/O ─────────────────────────────────────────────────────────────


def parse_args():
    p = argparse.ArgumentParser(description="Apply BTC-UAP to video files")

    p.add_argument("--uap", type=str, required=True,
                    help="Path to BTC-UAP tensor (.pt file)")
    p.add_argument("--video_dir", type=str, required=True,
                    help="Directory containing source videos")
    p.add_argument("--output_dir", type=str, default="./adversarial_videos",
                    help="Output directory for adversarial videos")
    p.add_argument("--codec", type=str, default="mp4v",
                    help="FourCC codec for output videos (default: mp4v)")
    p.add_argument("--ext", type=str, default=".mp4",
                    help="Output file extension (default: .mp4)")
    p.add_argument("--crf", type=int, default=23,
                    help="H.264 CRF quality when using ffmpeg "
                         "(0=best, 23=default, 51=worst). "
                         "Lower = better quality, larger files (default: 23)")

    # Temporal smoothing for imperceptibility
    p.add_argument("--smooth_sigma", type=float, default=0.0,
                    help="Gaussian smoothing sigma along time axis. "
                         "0 = off, try 0.5-2.0 for subtle smoothing (default: 0)")
    p.add_argument("--stretch", type=int, default=1,
                    help="Slow UAP playback by this factor with interpolation. "
                         "1 = off, 4 = each UAP frame spans 4 video frames (default: 1)")
    p.add_argument("--epsilon", type=float, default=None,
                    help="L-inf clamp bound after temporal smoothing. "
                         "Default: auto-detect from the (scaled) UAP's L-inf")
    p.add_argument("--scale", type=float, default=1.0,
                    help="Scale factor for perturbation intensity. "
                         "1.0 = original strength, 0.5 = half strength. "
                         "Train once at a large epsilon, then dial down at "
                         "apply time for different strength/imperceptibility "
                         "trade-offs (default: 1.0)")

    # Temporal order ablation flags (mutually exclusive)
    ablation = p.add_mutually_exclusive_group()
    ablation.add_argument("--shuffle_seed", type=int, default=None,
                          help="Randomly permute UAP frame order using this seed. "
                               "Tests whether VLMs are sensitive to temporal order.")
    ablation.add_argument("--static_frame", type=int, default=None,
                          help="Use only this UAP frame index for all video frames "
                               "(no temporal variation). Tests whether frame diversity matters.")
    ablation.add_argument("--reverse", action="store_true",
                          help="Reverse UAP frame order (31, 30, ..., 0). "
                               "Tests whether temporal directionality matters.")

    return p.parse_args()


def find_videos(video_dir):
    vdir = Path(video_dir)
    if not vdir.is_dir():
        print(f"Error: '{video_dir}' is not a directory.")
        sys.exit(1)

    # Search recursively so videos in subdirectories are found
    videos = sorted(
        p for p in vdir.rglob("*")
        if p.is_file() and p.suffix.lower() in VIDEO_EXTENSIONS
    )

    if not videos:
        all_files = [f for f in vdir.rglob("*") if f.is_file()]
        print(f"  Directory contents ({len(all_files)} files):")
        extensions = {}
        for f in all_files:
            ext = f.suffix.lower()
            extensions[ext] = extensions.get(ext, 0) + 1
        for ext, count in sorted(extensions.items()):
            print(f"    {ext or '(no extension)'}: {count} file(s)")
        print(f"  Looking for: {VIDEO_EXTENSIONS}")

    return videos


def create_video_writer(output_path, codec, fps, width, height):
    """
    Try to create a working VideoWriter with the given codec.
    Falls back through several codecs if the requested one fails.
    """
    codecs_to_try = [codec]

    for fallback in ["avc1", "mp4v", "XVID", "MJPG"]:
        if fallback not in codecs_to_try:
            codecs_to_try.append(fallback)

    ext_map = {
        "XVID": ".avi", "MJPG": ".avi", "mp4v": ".mp4",
        "avc1": ".mp4", "FFV1": ".avi",
    }

    for c in codecs_to_try:
        fourcc = cv2.VideoWriter_fourcc(*c)
        out = str(output_path)
        expected_ext = ext_map.get(c, ".avi")
        if Path(out).suffix.lower() != expected_ext:
            out = str(Path(out).with_suffix(expected_ext))

        writer = cv2.VideoWriter(out, fourcc, fps, (width, height))
        if writer.isOpened():
            return writer, Path(out), c
        writer.release()

    return None, None, None


def _ffmpeg_available():
    """Check if ffmpeg is on PATH."""
    return shutil.which("ffmpeg") is not None


def _open_ffmpeg_writer(output_path, fps, width, height, crf=23):
    """Open an ffmpeg subprocess that accepts raw BGR frames via stdin.

    Uses H.264 with CRF-based quality control for proper compression.
    """
    cmd = [
        "ffmpeg", "-y",
        "-f", "rawvideo", "-vcodec", "rawvideo",
        "-pix_fmt", "bgr24",
        "-s", f"{width}x{height}",
        "-r", str(fps),
        "-i", "-",
        "-c:v", "libx264", "-crf", str(crf),
        "-pix_fmt", "yuv420p",
        str(output_path),
    ]
    return subprocess.Popen(cmd, stdin=subprocess.PIPE,
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def apply_uap_to_video(video_path, delta_N_np, output_path, codec, N, stretch,
                        crf=23):
    """
    Read a video, add the (optionally smoothed) BTC-UAP, and write the result.

    Prefers piping frames to ffmpeg for proper H.264 compression.
    Falls back to OpenCV VideoWriter if ffmpeg is unavailable.
    """
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"  [WARNING] Cannot open: {video_path.name}")
        return False

    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total <= 0:
        cap.release()
        print(f"  [WARNING] No frames in: {video_path.name}")
        return False

    ffmpeg_proc = None
    writer = None
    actual_output = Path(output_path)

    if _ffmpeg_available():
        actual_output = actual_output.with_suffix(".mp4")
        ffmpeg_proc = _open_ffmpeg_writer(
            actual_output, fps, width, height, crf=crf,
        )
    else:
        writer, actual_output, used_codec = create_video_writer(
            output_path, codec, fps, width, height,
        )
        if writer is None:
            cap.release()
            print(f"  [WARNING] No working video codec found for: {video_path.name}")
            return False

    frame_idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        delta_frame = get_interpolated_frame(delta_N_np, frame_idx, N, stretch)
        delta_frame = delta_frame.transpose(1, 2, 0)  # (C,H,W) -> (H,W,C)

        if delta_frame.shape[0] != height or delta_frame.shape[1] != width:
            delta_frame = cv2.resize(delta_frame, (width, height),
                                     interpolation=cv2.INTER_LINEAR)

        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
        adv_frame = np.clip(frame_rgb + delta_frame, 0.0, 1.0)

        adv_bgr = cv2.cvtColor((adv_frame * 255).astype(np.uint8), cv2.COLOR_RGB2BGR)

        if ffmpeg_proc is not None:
            ffmpeg_proc.stdin.write(adv_bgr.tobytes())
        else:
            writer.write(adv_bgr)
        frame_idx += 1

    cap.release()

    if ffmpeg_proc is not None:
        ffmpeg_proc.stdin.close()
        ffmpeg_proc.wait()
        if ffmpeg_proc.returncode != 0:
            print(f"  [WARNING] ffmpeg encoding failed for: {video_path.name}")
            return False
    elif writer is not None:
        writer.release()

    if not actual_output.exists() or actual_output.stat().st_size == 0:
        print(f"  [WARNING] Output file is empty or missing: {actual_output}")
        return False

    return True


# ── Main ──────────────────────────────────────────────────────────────────


def main():
    args = parse_args()

    # ── Load BTC-UAP ──
    print(f"Loading BTC-UAP from {args.uap} …")
    delta_N = torch.load(args.uap, map_location="cpu", weights_only=True)
    N = delta_N.shape[0]
    print(f"  Shape: {list(delta_N.shape)}  (N={N}, "
          f"C={delta_N.shape[1]}, H={delta_N.shape[2]}, W={delta_N.shape[3]})")
    print(f"  L∞ norm: {delta_N.abs().max().item():.6f}")

    delta_N_np = delta_N.numpy().astype(np.float32)

    # ── Temporal order ablation ──
    if args.shuffle_seed is not None:
        rng = np.random.default_rng(args.shuffle_seed)
        perm = rng.permutation(N)
        delta_N_np = delta_N_np[perm]
        print(f"  ABLATION: Shuffled frame order (seed={args.shuffle_seed})")
        print(f"  Permutation: {perm.tolist()}")
    elif args.static_frame is not None:
        idx = args.static_frame % N
        delta_N_np = np.stack([delta_N_np[idx]] * N, axis=0)
        print(f"  ABLATION: Static frame {idx} repeated for all {N} positions")
    elif args.reverse:
        delta_N_np = delta_N_np[::-1].copy()
        print(f"  ABLATION: Reversed frame order (N-1, N-2, ..., 0)")

    # ── Scale perturbation intensity ──
    if args.scale != 1.0:
        delta_N_np *= args.scale
        print(f"  Scaled by {args.scale:.4f}  →  effective L∞ = "
              f"{np.abs(delta_N_np).max():.6f}")

    # ── Temporal smoothing ──
    if args.smooth_sigma > 0:
        smooth_eps = (args.epsilon if args.epsilon is not None
                      else float(np.abs(delta_N_np).max()))
        print(f"\nApplying temporal Gaussian smoothing (sigma={args.smooth_sigma}) …")
        delta_N_np = temporal_gaussian_smooth(delta_N_np, args.smooth_sigma, smooth_eps)
        print(f"  L∞ norm after smoothing: {np.abs(delta_N_np).max():.6f}")

    if args.stretch > 1:
        print(f"Stretch factor: {args.stretch}x  "
              f"(UAP cycle spans {N * args.stretch} video frames instead of {N})")

    print()

    # ── Find videos ──
    videos = find_videos(args.video_dir)
    print(f"Found {len(videos)} video(s) in {args.video_dir}")
    if not videos:
        print("Nothing to process. Exiting.")
        sys.exit(0)

    # ── Prepare output ──
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Test encoding ──
    if _ffmpeg_available():
        print(f"Using ffmpeg for H.264 encoding (CRF={args.crf}).\n")
    else:
        print("ffmpeg not found, falling back to OpenCV VideoWriter …")
        test_file = out_dir / ("codec_test" + args.ext)
        test_writer, actual_test_file, test_codec = create_video_writer(
            test_file, args.codec, 30.0, 64, 64,
        )
        if test_writer is None:
            print("ERROR: No working video codec found. Install ffmpeg or rebuild")
            print("       OpenCV with codec support:  pip install opencv-python-headless")
            sys.exit(1)
        else:
            test_writer.release()
            if actual_test_file is not None:
                actual_test_file.unlink(missing_ok=True)
            print(f"Codec OK ({test_codec}).\n")

    # ── Apply UAP to each video ──
    success = 0
    for video_path in tqdm(videos, desc="Applying BTC-UAP", unit="video"):
        out_name = video_path.stem + "_adv" + args.ext
        out_path = out_dir / out_name

        ok = apply_uap_to_video(
            video_path, delta_N_np, out_path, args.codec, N, args.stretch,
            crf=args.crf,
        )
        if ok:
            success += 1

    print(f"\nDone. {success}/{len(videos)} adversarial videos saved to {out_dir}")


if __name__ == "__main__":
    main()
